### ISSUE TITLE
Variable initialized before while moved to for-loop initializer 

### ISSUE THREAD

**Issue by blutorange** [babel/minify#742]
The simplify plugin seems to place variables declared and initialized before a while loop into a for loop, even if the variable is used again after the loop.

versions
```
babel-preset-minify@0.2.0
babel-cli@6.26.0
```

.babelrc
```
{
    "presets": [
        ["env", {"targets":{"browsers":["last 2 versions"]}}],
        ["minify", {}]
    ]
}
```
#### Input Code

```js
(function() {
     let count = 10;
     while (count++ < 20) {}
     return count;
})();
```

#### Actual Output

```bash
npx babel test.js  --out-file test.min.js
```

```js
"use strict";(function(){for(var a=10;20>a++;);return count})();
```

This gives a `Uncaught ReferenceError: count is not defined(…)`.

#### Expected Output

```js
"use strict";(function(){var a=10;while(20>a++){}return a})();
```

#### Details

It works as expected if I disabled the simplify plugin:
```
{
    "presets": [
        ["env", {
            "modules": false,
            "targets":{
"browsers": ["last 2 version"]
}
        }],
        ["minify", {
           "simplify": false
       }]
    ]
}

It also works if I change the input code as follows:

```js
(function() {
     let count = 10;
     0;
     while (count++ < 20) {}
     return count;
})();
```

Also, this

```js
(function(x) {
     let count = 10;
     while (x++ < 20) {}
     return count;
})(5);
```

becomes

```js
"use strict";(function(a){for(;20>a++;);return count})(5);
```

which removes the variable initialization to 10 completely.

This one also happens on [babeljs.io](http://babeljs.io/repl#?babili=true&browsers=&build=&builtIns=false&code_lz=BQMwrgdgxgLglgewsAHgSgAQG8BQH_4A2ApjBlApGQLwYCMADANx4EYDuAFnCRqgNT8MAHgwAmBpiwBfVgQBOpMPIjlKEGC2lpgAVjQsgA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Cbabili&prettier=false&targets=&version=6.26.0). It works correctly if I *either* turn off all presets *or* minify.

**Comment by boopathi** [comment]
This is fixed in #713 .

**Comment by mwilkins91** [comment]
With the latest   "babel-preset-minify": "^0.5.0" I still have this issue. This is the code block in question:

```

  String.prototype.lpad = function (padString, length) {
    let str = this;
    while (str.length < length) { str = padString + str; }
    return str;
  };

```

becomes

```

String.prototype.lpad = function(a, b) {
            for (var c = this; c.length < b; )
                c = (_readOnlyError("str"),
                a + c);
            return str
        }

```

which of course throws str is undefined. Any advice?
